#!/bin/bash

# Check if an argument is provided
if [ $# -eq 0 ]; then
    # No argument provided, run the lexer in REPL mode
    ./bin/gpp_lexer
else
    # Argument provided, run the lexer with the provided file
    ./bin/gpp_lexer "$1"
fi